//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT0002350:"Function",FLT721001:"A/c No",FLT721002:"PAAR Date Submission",FLT721003:"Cheque Date",FLT721004:"Amount",
FLT721005:"Charge",FLT721006:"Payee Name",FLT721007:"Chq no",FLT721008:"Request Date",FLT721009:"Charge(NPR)"};
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
