//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY

var jspRes={FLT721009:"Function Code",FLT721001:"AC/No",FLT921001:"Instrument No",FLT014741:"--SELECT--",FLT0002318:"A-Add",FLT0002326:"I-Inquiry",FLT0002320:"R-Reject by Verifier",FLT0002367:"V-VERIFY"};
//,FLT0002319:"M-Modify"
var jspResALT = {
};

var arrJspArr = new Array (jspRes, jspResALT);
var jspResArr = new litMap(arrJspArr);

//GENERATED BY CUSTOMIZATION GENERATOR.DO NOT MODIFY 
var jspErr={};
var jspErrALT = {
};

var arrJspErr = new Array (jspErr, jspErrALT);
var jspErrResArr = new litMap(arrJspErr);
