<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<%@ page import="applcommon.ProfileProperties" %>
<%@ page import="applcommon.ParseValue" %>
<%@ page import="FABCommon.SecurityInfo70"%>
<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
	SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

%>
<script>

var accId  = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accId",""))%>';
	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";
        var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
        var nrbSerialNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".nrbSerialNo",""))%>';
        var tranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranId",""))%>';
        var tranDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranDate_ui",""))%>';

	
	

	var cspotId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cspotId",""))%>';
	var cspotAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cspotAmt",""))%>';
	var intAmt = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".intAmt",""))%>';
	var cspotDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cspotDate_ui",""))%>';
	var prdInDays = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".prdInDays",""))%>';
	var matDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".matDate_ui",""))%>';




</script>

<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_pre_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("cust_post_evt.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("core_banking.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("resource_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("custom_common_functions.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>



<script language="javascript" src="../Renderer/custom/props/cspotProps.js"></script>

<script language="JavaScript">

	printBlock();
	printFooterBlock();
</script>

