<%--
//Generated by Customization WB Generator
//Do not edit this file directly.
//Instead, modify the properties in the tool and regenerate.
--%>
<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<%@ page import="java.sql.*"%>
<%@ page import = "java.io.*"%>

<%@ page import="applcommon.ParseValue" %>
<%@ page import="com.infy.bbu.jsputil.*"%>
<%@ taglib uri="taglib.tld" prefix="arjsp" %>
<%@ page import="FABCommon.SecurityInfo70"%>

<arjsp:init groupName="Customize" isEntryPoint="false" />

<%
	String sProfileId = ProfilesManager.getProfileInSession(session);
	String sSubGrpName = (String)ARJspCurr.getInput("subGroupName","");
	String sGrpName = ARJspCurr.getCurrentGroup();
	String sPopUpExceptionWindow = (String)ARJspCurr.getInput(sGrpName+".PopUpExceptionWindow" ,"false");
	String sReferralMode = (String)ARJspCurr.getInput("refSubMode" ,"");
	ARJspCurr.setInput(sGrpName+".PopUpExceptionWindow","false");
        SecurityInfo70 securityInfo = (SecurityInfo70)session.getAttribute("FinUserInfo");

%>

<script>

	var sPopUpExceptionWindow = '<%=sPopUpExceptionWindow%>';
	var sReferralMode = '<%=sReferralMode%>' ;
        var BODDate= "<%=(securityInfo.bodDate).substring(0,10)%>";

	var subGroupName = '<%=ParseValue.checkString(ARJspCurr.getInput("subGroupName",""))%>';
	var funcCode = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".funcCode",""))%>';
	var nrbSerialNo = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".nrbSerialNo",""))%>';
	var accId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".accId",""))%>';
	var tranId = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".tranId",""))%>';
	var cspotDate_ui = '<%=ParseValue.checkString(ARJspCurr.getInput(sSubGrpName+".cspotDate_ui",""))%>';
	

</script>

<script language="javascript" src="../Renderer/custom/props/cspotProps.js"></script>
<script language="javascript" src="../Renderer/javascripts/<%=VRPKeys.getFile("common_functions.js",sProfileId)%>" > </script>

<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showsolId.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSchmCodes.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showSchemeCode.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showEmplList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showAccountIdList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/javascripts/lists/<%=VRPKeys.getFile("showColtrlCodeList.js",sProfileId)%>"></script>
<script language="javascript" src="../Renderer/custom/javascripts/custom_functions.js"></script>


<script language="JavaScript">
	printBlock();
	printFooterBlock();
</script>

